//
//  Coordinate.swift
//  FootballKit
//
//  Created by João Pereira on 28/03/17.
//  Copyright © 2017 NSMyself. All rights reserved.
//

import Foundation

struct Coordinate: Equatable, Hashable {
    
    let x: Int
    let y: Int
    
    var hashValue: Int {
        return x.hashValue ^ y.hashValue
    }
    
    private init(x: Int, y: Int) {
        self.x = x
        self.y = y
    }
    
    // really wish i could do this dynamically...
    static let A1 = Coordinate(x: 0, y: 1)
    static let A2 = Coordinate(x: 0, y: 2)
    static let A3 = Coordinate(x: 0, y: 3)
    static let A4 = Coordinate(x: 0, y: 4)
    static let A5 = Coordinate(x: 0, y: 5)
    static let A6 = Coordinate(x: 0, y: 6)
    static let A7 = Coordinate(x: 0, y: 7)
    static let A8 = Coordinate(x: 0, y: 8)
    static let A9 = Coordinate(x: 0, y: 9)
    static let A10 = Coordinate(x: 0, y: 10)
    static let A11 = Coordinate(x: 0, y: 11)
    static let B1 = Coordinate(x: 1, y: 1)
    static let B2 = Coordinate(x: 1, y: 2)
    static let B3 = Coordinate(x: 1, y: 3)
    static let B4 = Coordinate(x: 1, y: 4)
    static let B5 = Coordinate(x: 1, y: 5)
    static let B6 = Coordinate(x: 1, y: 6)
    static let B7 = Coordinate(x: 1, y: 7)
    static let B8 = Coordinate(x: 1, y: 8)
    static let B9 = Coordinate(x: 1, y: 9)
    static let B10 = Coordinate(x: 1, y: 10)
    static let B11 = Coordinate(x: 1, y: 11)
    static let C1 = Coordinate(x: 2, y: 1)
    static let C2 = Coordinate(x: 2, y: 2)
    static let C3 = Coordinate(x: 2, y: 3)
    static let C4 = Coordinate(x: 2, y: 4)
    static let C5 = Coordinate(x: 2, y: 5)
    static let C6 = Coordinate(x: 2, y: 6)
    static let C7 = Coordinate(x: 2, y: 7)
    static let C8 = Coordinate(x: 2, y: 8)
    static let C9 = Coordinate(x: 2, y: 9)
    static let C10 = Coordinate(x: 2, y: 10)
    static let C11 = Coordinate(x: 2, y: 11)
    static let D1 = Coordinate(x: 3, y: 1)
    static let D2 = Coordinate(x: 3, y: 2)
    static let D3 = Coordinate(x: 3, y: 3)
    static let D4 = Coordinate(x: 3, y: 4)
    static let D5 = Coordinate(x: 3, y: 5)
    static let D6 = Coordinate(x: 3, y: 6)
    static let D7 = Coordinate(x: 3, y: 7)
    static let D8 = Coordinate(x: 3, y: 8)
    static let D9 = Coordinate(x: 3, y: 9)
    static let D10 = Coordinate(x: 3, y: 10)
    static let D11 = Coordinate(x: 3, y: 11)
    static let E1 = Coordinate(x: 4, y: 1)
    static let E2 = Coordinate(x: 4, y: 2)
    static let E3 = Coordinate(x: 4, y: 3)
    static let E4 = Coordinate(x: 4, y: 4)
    static let E5 = Coordinate(x: 4, y: 5)
    static let E6 = Coordinate(x: 4, y: 6)
    static let E7 = Coordinate(x: 4, y: 7)
    static let E8 = Coordinate(x: 4, y: 8)
    static let E9 = Coordinate(x: 4, y: 9)
    static let E10 = Coordinate(x: 4, y: 10)
    static let E11 = Coordinate(x: 4, y: 11)
    static let F1 = Coordinate(x: 5, y: 1)
    static let F2 = Coordinate(x: 5, y: 2)
    static let F3 = Coordinate(x: 5, y: 3)
    static let F4 = Coordinate(x: 5, y: 4)
    static let F5 = Coordinate(x: 5, y: 5)
    static let F6 = Coordinate(x: 5, y: 6)
    static let F7 = Coordinate(x: 5, y: 7)
    static let F8 = Coordinate(x: 5, y: 8)
    static let F9 = Coordinate(x: 5, y: 9)
    static let F10 = Coordinate(x: 5, y: 10)
    static let F11 = Coordinate(x: 5, y: 11)
    static let G1 = Coordinate(x: 6, y: 1)
    static let G2 = Coordinate(x: 6, y: 2)
    static let G3 = Coordinate(x: 6, y: 3)
    static let G4 = Coordinate(x: 6, y: 4)
    static let G5 = Coordinate(x: 6, y: 5)
    static let G6 = Coordinate(x: 6, y: 6)
    static let G7 = Coordinate(x: 6, y: 7)
    static let G8 = Coordinate(x: 6, y: 8)
    static let G9 = Coordinate(x: 6, y: 9)
    static let G10 = Coordinate(x: 6, y: 10)
    static let G11 = Coordinate(x: 6, y: 11)
    static let H1 = Coordinate(x: 7, y: 1)
    static let H2 = Coordinate(x: 7, y: 2)
    static let H3 = Coordinate(x: 7, y: 3)
    static let H4 = Coordinate(x: 7, y: 4)
    static let H5 = Coordinate(x: 7, y: 5)
    static let H6 = Coordinate(x: 7, y: 6)
    static let H7 = Coordinate(x: 7, y: 7)
    static let H8 = Coordinate(x: 7, y: 8)
    static let H9 = Coordinate(x: 7, y: 9)
    static let H10 = Coordinate(x: 7, y: 10)
    static let H11 = Coordinate(x: 7, y: 11)
    static let I1 = Coordinate(x: 8, y: 1)
    static let I2 = Coordinate(x: 8, y: 2)
    static let I3 = Coordinate(x: 8, y: 3)
    static let I4 = Coordinate(x: 8, y: 4)
    static let I5 = Coordinate(x: 8, y: 5)
    static let I6 = Coordinate(x: 8, y: 6)
    static let I7 = Coordinate(x: 8, y: 7)
    static let I8 = Coordinate(x: 8, y: 8)
    static let I9 = Coordinate(x: 8, y: 9)
    static let I10 = Coordinate(x: 8, y: 10)
    static let I11 = Coordinate(x: 8, y: 11)
    static let J1 = Coordinate(x: 9, y: 1)
    static let J2 = Coordinate(x: 9, y: 2)
    static let J3 = Coordinate(x: 9, y: 3)
    static let J4 = Coordinate(x: 9, y: 4)
    static let J5 = Coordinate(x: 9, y: 5)
    static let J6 = Coordinate(x: 9, y: 6)
    static let J7 = Coordinate(x: 9, y: 7)
    static let J8 = Coordinate(x: 9, y: 8)
    static let J9 = Coordinate(x: 9, y: 9)
    static let J10 = Coordinate(x: 9, y: 10)
    static let J11 = Coordinate(x: 9, y: 11)
    static let K1 = Coordinate(x: 10, y: 1)
    static let K2 = Coordinate(x: 10, y: 2)
    static let K3 = Coordinate(x: 10, y: 3)
    static let K4 = Coordinate(x: 10, y: 4)
    static let K5 = Coordinate(x: 10, y: 5)
    static let K6 = Coordinate(x: 10, y: 6)
    static let K7 = Coordinate(x: 10, y: 7)
    static let K8 = Coordinate(x: 10, y: 8)
    static let K9 = Coordinate(x: 10, y: 9)
    static let K10 = Coordinate(x: 10, y: 10)
    static let K11 = Coordinate(x: 10, y: 11)
    static let L1 = Coordinate(x: 11, y: 1)
    static let L2 = Coordinate(x: 11, y: 2)
    static let L3 = Coordinate(x: 11, y: 3)
    static let L4 = Coordinate(x: 11, y: 4)
    static let L5 = Coordinate(x: 11, y: 5)
    static let L6 = Coordinate(x: 11, y: 6)
    static let L7 = Coordinate(x: 11, y: 7)
    static let L8 = Coordinate(x: 11, y: 8)
    static let L9 = Coordinate(x: 11, y: 9)
    static let L10 = Coordinate(x: 11, y: 10)
    static let L11 = Coordinate(x: 11, y: 11)
    static let M1 = Coordinate(x: 12, y: 1)
    static let M2 = Coordinate(x: 12, y: 2)
    static let M3 = Coordinate(x: 12, y: 3)
    static let M4 = Coordinate(x: 12, y: 4)
    static let M5 = Coordinate(x: 12, y: 5)
    static let M6 = Coordinate(x: 12, y: 6)
    static let M7 = Coordinate(x: 12, y: 7)
    static let M8 = Coordinate(x: 12, y: 8)
    static let M9 = Coordinate(x: 12, y: 9)
    static let M10 = Coordinate(x: 12, y: 10)
    static let M11 = Coordinate(x: 12, y: 11)
    static let N1 = Coordinate(x: 13, y: 1)
    static let N2 = Coordinate(x: 13, y: 2)
    static let N3 = Coordinate(x: 13, y: 3)
    static let N4 = Coordinate(x: 13, y: 4)
    static let N5 = Coordinate(x: 13, y: 5)
    static let N6 = Coordinate(x: 13, y: 6)
    static let N7 = Coordinate(x: 13, y: 7)
    static let N8 = Coordinate(x: 13, y: 8)
    static let N9 = Coordinate(x: 13, y: 9)
    static let N10 = Coordinate(x: 13, y: 10)
    static let N11 = Coordinate(x: 13, y: 11)
    static let O1 = Coordinate(x: 14, y: 1)
    static let O2 = Coordinate(x: 14, y: 2)
    static let O3 = Coordinate(x: 14, y: 3)
    static let O4 = Coordinate(x: 14, y: 4)
    static let O5 = Coordinate(x: 14, y: 5)
    static let O6 = Coordinate(x: 14, y: 6)
    static let O7 = Coordinate(x: 14, y: 7)
    static let O8 = Coordinate(x: 14, y: 8)
    static let O9 = Coordinate(x: 14, y: 9)
    static let O10 = Coordinate(x: 14, y: 10)
    static let O11 = Coordinate(x: 14, y: 11)
    static let P1 = Coordinate(x: 15, y: 1)
    static let P2 = Coordinate(x: 15, y: 2)
    static let P3 = Coordinate(x: 15, y: 3)
    static let P4 = Coordinate(x: 15, y: 4)
    static let P5 = Coordinate(x: 15, y: 5)
    static let P6 = Coordinate(x: 15, y: 6)
    static let P7 = Coordinate(x: 15, y: 7)
    static let P8 = Coordinate(x: 15, y: 8)
    static let P9 = Coordinate(x: 15, y: 9)
    static let P10 = Coordinate(x: 15, y: 10)
    static let P11 = Coordinate(x: 15, y: 11)
    static let Q1 = Coordinate(x: 16, y: 1)
    static let Q2 = Coordinate(x: 16, y: 2)
    static let Q3 = Coordinate(x: 16, y: 3)
    static let Q4 = Coordinate(x: 16, y: 4)
    static let Q5 = Coordinate(x: 16, y: 5)
    static let Q6 = Coordinate(x: 16, y: 6)
    static let Q7 = Coordinate(x: 16, y: 7)
    static let Q8 = Coordinate(x: 16, y: 8)
    static let Q9 = Coordinate(x: 16, y: 9)
    static let Q10 = Coordinate(x: 16, y: 10)
    static let Q11 = Coordinate(x: 16, y: 11)
    static let R1 = Coordinate(x: 17, y: 1)
    static let R2 = Coordinate(x: 17, y: 2)
    static let R3 = Coordinate(x: 17, y: 3)
    static let R4 = Coordinate(x: 17, y: 4)
    static let R5 = Coordinate(x: 17, y: 5)
    static let R6 = Coordinate(x: 17, y: 6)
    static let R7 = Coordinate(x: 17, y: 7)
    static let R8 = Coordinate(x: 17, y: 8)
    static let R9 = Coordinate(x: 17, y: 9)
    static let R10 = Coordinate(x: 17, y: 10)
    static let R11 = Coordinate(x: 17, y: 11)
}

extension Coordinate {
    static func == (lhs:Coordinate, rhs:Coordinate) -> Bool {
        return lhs.x == rhs.x && lhs.y == rhs.y
    }
}
